version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "npm"
    directory: "/gramwrite/native/harper"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:10"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:20"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
